// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsProvider } from "@/core/hooks";
import "@/assets/styles/app/scss/app.scss";
import PageFooter from "@/components/shared/PageFooter";
import PageHeader from "@/components/shared/PageHeader";
import CartProvider from "@/core/hooks/CartContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ProductsProvider>
          <CartProvider>
            <div className="w-[100vw] m-0 p-0 border-none box-border transition duration-300 bg-secondary-light dark:bg-primary-dark">
              <PageHeader />
              {children}
              <PageFooter />
            </div>
          </CartProvider>
        </ProductsProvider>
      </body>
    </html>
  );
}
